---
# tasks file for lighthouse-role
- name: Install lighthouse
  hosts: lighthouse
  tasks:
    - name: Clone repository
      become: true
      ansible.builtin.git:
        repo: "{{ lighthouse_url }}"
        dest: "{{ lighthouse_dir }}"
        version: master
    - name: Apply config
      become: true
      ansible.builtin.template:
        src: lighthouse-nginx.conf.j2
        dest: /etc/nginx/conf.d/lighthouse.conf
        mode: 0644
      notify: Nginx reload
